command: bash ../job_files/train_vit_cifar_baseline.sh
description: imageGPT classify
is_parent: false
name: ViT small + cifar100, grpc off with -m torch.distributed.launch
tags: ['cifar100', 'vit small']
setup_command: 'wget https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz; tar -xzf cifar-100-python.tar.gz'
